name = "the-kut-shoppe"
account_id = "ef97f4e6cee13846035d6e5982999bd8"
pages_build_output_dir = "dist-pages"
compatibility_date = "2026-09-09"
compatibility_flags = ["nodejs_compat"]

[vars]
ACCOUNTS_ENABLED = "false"
CUSTOMER_BOOKING_ENABLED = "false"
STAFF_OPERATIONS_ENABLED = "false"
STAFF_SETUP_ENABLED = "false"
COMMERCE_ENABLED = "false"
CASH_SALES_ENABLED = "false"
APPOINTMENT_EMAIL_ENABLED = "false"

[[services]]
binding = "API"
service = "the-kut-shoppe"

[env.preview]
services = []
