import { useEffect, useState, useSyncExternalStore } from 'react';
import { accountApi, getCustomerSession, loadCustomerSession, subscribeToCustomerSession } from '../data/customer-api';
import { loadCatalog, readProducts, productCategories } from '../data/live-storefront';
import type { StoreProduct, StoreOrder } from '../data/storefront';
import { StorefrontV5 } from './LiveStorefrontV5';
import { CartPageV4 } from './LiveCartPageV4';
import { CheckoutPageV5, ProductDetailPageV5, OrderReceiptV5 } from './LiveCommerceCustomerV5';
import { CustomerAccount } from './CustomerAccount';
import { StaffAuthenticator } from './StaffAuthenticator';

const message=(error:unknown)=>error instanceof Error?error.message:'Please try again.';
type ManagedOrder = StoreOrder & {canProcess:boolean;saleId?:string|null;financialState?:string};
type ProductInput={id:string;name:string;slug:string;category:string;description:string;baseSku:string;status:string;pickupEnabled:boolean;shippingEnabled:boolean;imageUrl:string;imageAlt:string;variants:Array<{id:string;name:string;sku:string;priceCents:number;stockOnHand:number;active:boolean}>};
const draft=():ProductInput=>({id:crypto.randomUUID(),name:'',slug:'',category:'Grooming',description:'',baseSku:'',status:'draft',pickupEnabled:true,shippingEnabled:false,imageUrl:'',imageAlt:'',variants:[{id:crypto.randomUUID(),name:'Default',sku:'',priceCents:0,stockOnHand:0,active:true}]});
function ProductEditor({product,revision,onSaved}:{product:ProductInput;revision:number;onSaved:()=>void}){
  const [value,setValue]=useState(product);const [error,setError]=useState('');const [working,setWorking]=useState(false);
  return <form className="customer-form" onSubmit={async event=>{event.preventDefault();if(working)return;setWorking(true);setError('');try{await accountApi('/me/commerce/products',{product:value,revision});onSaved();}catch(e){setError(message(e));}finally{setWorking(false);}}}><fieldset disabled={working}><legend>Product details</legend>
    {(['name','slug','baseSku','description'] as const).map(key=><label key={key}>{({name:'Product name',slug:'URL name (letters, numbers, hyphens)',baseSku:'Product SKU',description:'Description'})[key]}<input required={key!=='description'} maxLength={key==='description'?2000:key==='name'?150:80} value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}
    <label>Category<select value={value.category} onChange={e=>setValue({...value,category:e.target.value})}>{productCategories.map(c=><option key={c}>{c}</option>)}</select></label>
    <label>Publication<select value={value.status} onChange={e=>setValue({...value,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>
    <label><input type="checkbox" checked={value.pickupEnabled} onChange={e=>setValue({...value,pickupEnabled:e.target.checked})}/>Allow pickup requests</label><label><input type="checkbox" checked={value.shippingEnabled} onChange={e=>setValue({...value,shippingEnabled:e.target.checked})}/>Allow shipping requests</label>
    <label>Image URL<input type="url" value={value.imageUrl} onChange={e=>setValue({...value,imageUrl:e.target.value})}/><small>Use the shop website or its current image CDN.</small></label><label>Image description<input value={value.imageAlt} maxLength={200} onChange={e=>setValue({...value,imageAlt:e.target.value})}/></label>
    <h3>Variants and inventory</h3><p>Stock on hand includes quantities reserved by open order requests. Deactivate old variants instead of deleting them.</p>
    {value.variants.map((v,index)=><fieldset key={v.id}><legend>Variant {index+1}</legend>{(['name','sku'] as const).map(key=><label key={key}>{key==='name'?'Variant name':'Variant SKU'}<input required maxLength={80} value={v[key]} onChange={e=>setValue({...value,variants:value.variants.map((old,i)=>i===index?{...old,[key]:e.target.value}:old)})}/></label>)}<label>Price ($)<input type="number" min="0" step="0.01" required value={v.priceCents/100} onChange={e=>setValue({...value,variants:value.variants.map((old,i)=>i===index?{...old,priceCents:Math.round(Number(e.target.value)*100)}:old)})}/></label><label>Stock on hand<input type="number" min="0" step="1" required value={v.stockOnHand} onChange={e=>setValue({...value,variants:value.variants.map((old,i)=>i===index?{...old,stockOnHand:Number(e.target.value)}:old)})}/></label><label><input type="checkbox" checked={v.active} onChange={e=>setValue({...value,variants:value.variants.map((old,i)=>i===index?{...old,active:e.target.checked}:old)})}/>Active variant</label></fieldset>)}
    <button type="button" className="button button-secondary" disabled={value.variants.length>=10} onClick={()=>setValue({...value,variants:[...value.variants,{id:crypto.randomUUID(),name:'',sku:'',priceCents:0,stockOnHand:0,active:true}]})}>Add variant</button>
    {error?<p role="alert" className="form-error">{error} Reload the catalog before retrying if another change was saved.</p>:null}<button className="button">{working?'Saving…':'Save product'}</button><button type="button" className="text-button" onClick={onSaved}>Back to catalog</button>
  </fieldset></form>;
}
function ProductAdmin(){
  const [data,setData]=useState<{products:StoreProduct[];revision:number}|null>(null);const [editing,setEditing]=useState<ProductInput|null>(null);const [error,setError]=useState('');const [attempt,setAttempt]=useState(0);
  useEffect(()=>{let active=true;void accountApi<{products:StoreProduct[];revision:number}>('/me/commerce/products').then(d=>{if(active)setData(d);}).catch(e=>{if(active){setData(null);setError(message(e));}});return()=>{active=false;};},[attempt]);
  const refresh=()=>{setData(null);setEditing(null);setError('');setAttempt(v=>v+1);};
  return <><div className="customer-section-heading"><h1>Manage products</h1><a href="/admin/orders">Manage orders</a><a href="/shop">View shop</a></div>{error?<p role="alert">{error}</p>:null}{editing&&data?<ProductEditor key={editing.id} product={editing} revision={data.revision} onSaved={refresh}/>:data?<><button className="button" onClick={()=>setEditing(draft())}>Add product</button><ul className="customer-records">{data.products.map(p=><li key={p.id}><div><strong>{p.name}</strong><p>{p.status} · {p.variants.length} variants</p></div><button className="button button-secondary" onClick={()=>setEditing({id:p.id,name:p.name,slug:p.slug,category:p.category,description:p.description,baseSku:p.baseSku,status:p.status,pickupEnabled:p.pickupEnabled,shippingEnabled:p.shippingEnabled,imageUrl:p.images[0]?.src??'',imageAlt:p.images[0]?.alt??'',variants:p.variants.map(v=>({id:v.id,name:v.name,sku:v.sku,priceCents:v.priceCents,stockOnHand:v.stockOnHand,active:v.active}))})}>Edit product</button></li>)}</ul>{!data.products.length?<p>Add your first product, its variants and inventory, then publish it to the shop.</p>:null}</>:!error?<p role="status">Loading catalog…</p>:null}<button className="text-button" onClick={refresh}>Refresh catalog</button></>;
}
function OrderAdmin(){
  const [data,setData]=useState<{orders:ManagedOrder[];revision:number;more:boolean}|null>(null);const [error,setError]=useState('');const [attempt,setAttempt]=useState(0);const [working,setWorking]=useState(false);const [tracking,setTracking]=useState<Record<string,string>>({});
  useEffect(()=>{let active=true;void accountApi<{orders:ManagedOrder[];revision:number;more:boolean}>('/me/commerce/orders').then(d=>{if(active)setData(d);}).catch(e=>{if(active){setData(null);setError(message(e));}});return()=>{active=false;};},[attempt]);
  const refresh=()=>{setData(null);setError('');setAttempt(v=>v+1);};
  const update=async(order:StoreOrder,status:string)=>{if(working||!data)return;setWorking(true);try{await accountApi(`/me/commerce/orders/${order.id}`,{status,revision:data.revision,trackingNumber:tracking[order.id]??order.trackingNumber});refresh();}catch(e){setError(message(e));}finally{setWorking(false);}};
  return <><div className="customer-section-heading"><h1>Order requests</h1><a href="/admin/products">Manage products</a></div><p>Orders begin as unpaid requests. Review the linked sale and receipts before supplying an order. Fulfillment status does not record payment. Confirm tax and any shipping charges separately.</p>{error?<p role="alert" className="form-error">{error}</p>:null}{data?data.orders.map(o=>{const flow=o.fulfillment==='pickup'?['submitted','accepted','preparing','ready-for-pickup','completed']:['payment-required','accepted','preparing','shipped','completed'];const next=flow[flow.indexOf(o.status)+1];return <article key={o.id} className="customer-overview-panel"><OrderReceiptV5 order={o} products={readProducts()} accountMode/><p>Payment: {(o.financialState??'not_finalized').replaceAll('_',' ')}{o.saleId ? <> · <a href={`/account?view=counter&sale=${encodeURIComponent(o.saleId)}`}>Open sale and receipts</a></> : null}</p><p>Contact: {o.customer.name} · {o.customer.email} · {o.customer.phone}</p>{!['cancelled','declined','refunded','paid'].includes(o.status) ? <p><a href={`/account?view=sales&order=${encodeURIComponent(o.id)}`}>Prepare sale estimate</a></p> : null}{o.canProcess&&next&&flow.includes(o.status)?<div className="customer-form"><label>Tracking number<input value={tracking[o.id]??o.trackingNumber} onChange={e=>setTracking({...tracking,[o.id]:e.target.value})}/></label><div className="customer-form-actions"><button className="button" disabled={working} onClick={()=>void update(o,next)}>{next==='accepted'?'Accept request':`Mark ${next.replaceAll('-',' ')}`}</button>{o.status!=='shipped'?<button className="button button-secondary" disabled={working} onClick={()=>{if(window.confirm('Cancel this request and release its reserved inventory?'))void update(o,'cancelled');}}>Cancel request</button>:null}</div></div>:null}</article>;}):!error?<p role="status">Loading order requests…</p>:null}{data&&!data.orders.length?<p>No order requests yet.</p>:null}{data?.more?<p>Showing the first 100 orders, with open requests first.</p>:null}<button className="text-button" disabled={working} onClick={refresh}>Refresh orders</button></>;
}
export function LiveCommerce({path}:{path:string}){
  const account=useSyncExternalStore(subscribeToCustomerSession,getCustomerSession,()=>null);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [attempt,setAttempt]=useState(0);
  useEffect(()=>{let active=true;void Promise.all([loadCatalog(),loadCustomerSession().catch(()=>null)]).then(()=>{if(active)setReady(true);}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[attempt]);
  if(!ready)return <section className="section customer-account"><div className="container"><h1>Shop</h1>{error?<><p role="alert">{error}</p><button className="button" onClick={()=>{setError('');setAttempt(v=>v+1);}}>Try again</button></>:<p role="status">Opening the shop…</p>}</div></section>;
  if(path.startsWith('/admin/'))return !account?<CustomerAccount/>:<section className="section customer-account"><div className="container route-wide">{['owner','manager','developer'].includes(account.role)?<StaffAuthenticator>{path==='/admin/products'?<ProductAdmin/>:<OrderAdmin/>}</StaffAuthenticator>:<><h1>Store management</h1><p>Your account does not have store management access.</p><a href="/shop">Return to shop</a></>}</div></section>;
  if(path==='/cart')return <CartPageV4/>;if(path==='/checkout')return account?<CheckoutPageV5/>:<CustomerAccount/>;if(path.startsWith('/shop/'))return <ProductDetailPageV5 slug={decodeURIComponent(path.slice(6))}/>;return <StorefrontV5/>;
}
